### ISSUE TITLE
New update needed

### ISSUE THREAD

**Issue by Beardy18** [Umbranoxio/BeatSaberModInstaller#101]
Because of the new game update the other day the mod you have no longer works on the game can we please get and updated working version?

**Comment by BotMaster3000** [comment]
Seems like we need to use the old 0.12.2 Beta-Branch until its updated

**Comment by fr34q** [comment]
See this alternative mod installer: https://github.com/lolPants/modsaber-installer/releases
That one is updated and works with the new version. Not all mods work yet of course, but the base is working.

**Comment by ghost** [comment]
Is there no update on this mod yet? Songs still don't show - it is an empty folder.

**Comment by flamingtigers** [comment]
> See this alternative mod installer: https://github.com/lolPants/modsaber-installer/releases
> That one is updated and works with the new version. Not all mods work yet of course, but the base is working.

Thank you! This has saved the night! Hundreds of new songs. I appreciate it!

**Comment by cristan** [comment]
ModSaber Installer is paid now, so an update would be highly appreciated.
