### ISSUE TITLE
song browser not in new mod update rly need it help

### ISSUE THREAD

**Issue by nxnee** [Umbranoxio/BeatSaberModInstaller#104]

**Comment by stevemazg** [comment]
Just click on Extras (250 songs). Still lots missing though, update required asap :(

**Comment by phiresky** [comment]
duplicate of #101. you should learn how github works before spamming people with emails.

**Comment by notyoyoma** [comment]
Hey @nxnee, If you're still dealing with this issue, @megalon explained the current state of the project [here](https://github.com/Umbranoxio/BeatSaberModInstaller/issues/103#issuecomment-474804108).

TLDR: [This new repo](https://github.com/lolPants/modsaber-installer/) should work, and get you playing again
