### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by LuckyWaffles121** [Umbranoxio/BeatSaberModInstaller#105]
An update came out, yay. One problem that always occurs when an update happens, mod doesn't work. You guys will need to make a new mod so it could work with update 0.13.0p1. I know it came out yesterday, but I miss my mods!

**Comment by flamingtigers** [comment]
Prepare to get jumped all over. There are a few assholes that are about to attack you. @phireski is one of them. Just letting you know.

**Comment by notyoyoma** [comment]
Hey @LuckyWaffles121 this repository isn't being actively maintained, so there likely won't be an update to the code here for awhile.

There is a similar project [here](https://github.com/lolPants/modsaber-installer/) that should get you playing again quickly.

Quick note, if you intend to submit future issues on github, it's best to read through all recent issues to make sure that nobody has already reported your issue. If there's already a duplicate (in this case, issue #101 ) you can pile on to that issue, and add any details that may help. That really helps the developers (when they are active ) by giving them a clear idea of how many different things there are to work on.
