### ISSUE TITLE
Crashes after running for 5 seconds

### ISSUE THREAD

**Issue by ghost** [Umbranoxio/BeatSaberModInstaller#107]
Hi, the mod manager crashes after about 5 seconds of running.

**Comment by Atemu** [comment]
I'm not the only one then

**Comment by Itay1787** [comment]
modsaber Is dead!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by RubenVon** [comment]
Yup I'm getting this issue also, please fix asap! just bought beatsaber but it's kinda pointless without mods... if anyone finds a fix/solution please let me know :)

**Comment by aidanbobhog** [comment]
WHYYYY
