### ISSUE TITLE
mods still up?

### ISSUE THREAD

**Issue by SKidmaak** [Umbranoxio/BeatSaberModInstaller#108]
it looks like mod saber is down and i think for good where else are we supposed to get mods?

**Comment by megalon** [comment]
ModSaber is currently down indefinitely.

We are working on a new mod sharing solution, but for the time being, mods are being shared on the Discord server.

Please see the #server-announcements channel
https://discord.gg/beatsabermods

**Comment by SKidmaak** [comment]
i followed the things in the discord but im unsure how to do it when it was just some writing that i could only copy and paste

**Comment by megalon** [comment]
Here are the two links

**Download links**
Here's a link to all the mods that were on ModSaber as of this morning https://pastebin.com/Bcm85dpd

**Install instructions**
Here are manual instructions to installing mods: https://wiki.assistant.moe/beginners-guide

However, this may change soon when we get another solution up, so please check back on the Discord to stay updated.
