### ISSUE TITLE
Program runs into index out of range exception after path selection

### ISSUE THREAD

**Issue by rwolfdev** [Umbranoxio/BeatSaberModInstaller#109]
Hey guys,

I have newly downloaded BeatSaberModInstaller and selected the path to my beatsaber installation, but after the selection it crashes. My Visual Studio JIT Debugger tells me its a IndexOutOfRange Exception. 

If I can help you in any way, let me know!

Best regards,
Robert

**Comment by Aurailus** [comment]
I also am having this issue!

**Comment by phroggar** [comment]
Check the Manager here: https://github.com/beat-saber-modding-group/BeatSaberModInstaller/
You may also want to report new issues there if it still occurs.
