### ISSUE TITLE
"ScoreSaber" is not installed.

### ISSUE THREAD

**Issue by Tl1000sm1234** [Umbranoxio/BeatSaberModInstaller#11]
Hello,

"ScoreSaber" is not installed.
After manual installation in the correct folder "C:\Program Files\Oculus\Software\Software\hyperbolic-magnetism-beat-saber\Plugins\UnofficialLeaderBoardPluginOculus.dll" it works.

**Comment by Umbranoxio** [comment]
Seems like when I updated the UI the checkboxes got broken, sorry it took so long to fix.
