### ISSUE TITLE
 Execution ends without a message.

### ISSUE THREAD

**Issue by artbiit** [Umbranoxio/BeatSaberModInstaller#110]
OS : Windows10

**Comment by MarshallMac** [comment]
Same behavior on my machine. If any log files are needed I can provide.

**Comment by artbiit** [comment]
Exits without a log or message. "Status: Loading game version ..." has only a common point of ending

**Comment by almarax** [comment]
same problem

**Comment by IleeneFudge** [comment]
same thing here.  closes without warning.

**Comment by Kyle-Newton** [comment]
Same
