### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rtgs1967** [Umbranoxio/BeatSaberModInstaller#112]
Manager launches but after a moment or two it crashes with no warning or error. Tried running in different compatibility modes as well as administrator.

**Comment by IleeneFudge** [comment]
having trouble in general updating and trying to use the mod. what do I do now?

**Comment by Syberdoor** [comment]
The program crashes because it is no longer supported and modsaber is shut down (https://www.modsaber.org/)
you can use this installer instead:
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/

**Comment by Zamundaaa** [comment]
Soo am I just blind or is there really no executable to download? One has to compile it manually?

**Comment by Syberdoor** [comment]
should be under
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases

**Comment by Zamundaaa** [comment]
Thanks.
