### ISSUE TITLE
Request Timeout

### ISSUE THREAD

**Issue by ZillionPrey** [Umbranoxio/BeatSaberModInstaller#12]
When i try to install songs via the game, I often get "request timeout".
It's quite annoying to go to the pc everytime i want to download a song that i like.

**Comment by Umbranoxio** [comment]
This project is for installing the mods only, not support for existing mods, it sounds like you have an issue with the BeatSaverDownloader here: https://github.com/andruzzzhka/BeatSaverDownloader

I'll be closing this issue, feel free to create an issue over at the repo linked above.
