### ISSUE TITLE
The Song loader is only active for a min.

### ISSUE THREAD

**Issue by Shaklton** [Umbranoxio/BeatSaberModInstaller#15]
I start the game and I can play one map before beat saber reverts to an un-modded capacity. The little in game beat-saver button that took you to the map download screen is not there anymore. Basically, i can only play maps I have already downloaded and I can only play one unless i want to restart the game over and over again to load the list again.

**Comment by ponchoandlefty** [comment]
Same problem here

**Comment by UnoriginalOrion** [comment]
Same problem here, but with a twist - my multiplayer button is lifted and is barely visible because of it

**Comment by UgDuck989** [comment]
I am having the same problem including the lifted button and it doesn't keep track of the scores I play on modded songs.

**Comment by PugTechnology** [comment]
I had this issue as well but this was because I did not clear my plugins folder before I installed the updated exe.

1. Delete your plugins folder
2. Re-run the .exe to install desired mods

**Comment by Umbranoxio** [comment]
I guess nobody took the time to read the announcements post properly, delete all your plugins, then run the mod installer.
