### ISSUE TITLE
Every time i install your mod installer, the game doesn't even let me select anything.

### ISSUE THREAD

**Issue by ceakickers** [Umbranoxio/BeatSaberModInstaller#17]

**Comment by ma-rahmati** [comment]
same problem in new version

**Comment by pcnorden** [comment]
I don't try to be mean or angry in any way, but holy fuck this is vague information!

To put in perspective what the owner gets is like this: Imagine that you had a sickness so you go to the doctor to get it diagnosed.  
When you meet the doctor, you tell him
>"I'm sick, please tell me what sickness I have".

The doctor can't diagnose your problem with only that, so he asks you
>"What symptoms do you experience?"

And another patient chips up
>"Same problem in me too!"

The doctor can't diagnose you with that information, so he ignores you thinking you are just taking up his time and your issue will not be brought to light.

***

So, incase I could help (I'm not the repository owner, so I can't push code only add a pull request) I would need:
* OS
* Beat saber version
* If you have installed beat saber on a network share

Also, please try to do a clean install of beat saber then try the mod installer with only the songloader.

Take care!

**Comment by Naeviss** [comment]
Hi same here, 
more accurately the pointer does not hit anything, just points toward the void and I can't select a thing after installing the songloader and only the songloader. 

    OS:  win10 
    Beat saber version: where do I check that? 
    If you have installed beat saber on a network share: no


thank you :) 

//english isnt my native, be gentle, if something's not clear scream at me :D

**Comment by pcnorden** [comment]
@Naeviss Alright, that's a lot more info than before and thanks a lot for supplying it =D

Due to the problem only appearing with the songloader installed, it seems like the problem is with the songloader mod itself, but to make sure please do the steps outlined below in case you have the time =)

"Sorry if this will take more time for you and maybe making a mess in the folders, but can you please try to install the songloader mod manually (on the latest release there is a how-to [on the releases page](https://github.com/xyonico/BeatSaberSongLoader/releases)) on a clean install of beat saber?"

If that also doesn't work, it's defenitive proof that the issue lies in the songloader mod itself.

Take care =)

**Comment by Naeviss** [comment]
@pcnorden  I did it all, as written, now there're lightsabers but no pointers :( 

Thank you for your quick reply x"D I hope I helped some

**Comment by pcnorden** [comment]
Glad I could be of assistance =)

Hopefully you will resolve your problem soon =D

**Comment by ceakickers** [comment]
Hey bois, I was able to fix mine and also be able to get all mods on there,
I guess I was missing a game file for some reason, the only other issue I'm
having is that any time I want to do a nodded song, I have to restart for
some reason

**Comment by RomkaR10** [comment]
Hey. I have this problem too. After installing this mod, game doesn't even let me select anything. Please, help me!!!!

**Comment by pcnorden** [comment]
@RomkaR10 As we have concluded above, this is not the github issue page to put it in. This is pureley the mods fault, not the mod installer. Please try to update and if that does not work, please open a issue over at the modloader github page.

Take care and I hope that you fix it =)

**Comment by RomkaR10** [comment]
Maybe the problem is in the game itself? Because I downloaded the cracked version?

**Comment by MuzikxMonkey** [comment]
Using a pirated version?? Then yeah. You wont have the up to date stuff. This mod was built for a whole different type of game structure.
