### ISSUE TITLE
Play button greyed out after deleting a song

### ISSUE THREAD

**Issue by Unixsystem13** [Umbranoxio/BeatSaberModInstaller#19]
In the song selection menu, if you delete a song, its "Play" button gets greyed out (as expected). However, the play button also becomes greyed out for every other song in the list, even if you back out and reenter the menu. Restarting the game seems to be the only fix.

**Comment by Umbranoxio** [comment]
The mod installer only installs mods, it's not the creator of the mod itself, please create an issue on the repo related to your issue.
