### ISSUE TITLE
Have to find the installation folder each time

### ISSUE THREAD

**Issue by OmiCron07** [Umbranoxio/BeatSaberModInstaller#20]
Each time I run the mod installer, I have to browse to the installed directory. What is the check that I can fix my game installation?

**Comment by OmiCron07** [comment]
I checked the source code and I know why it does not work. My key InitialAppLibrary points to "S:\Games\Oculus Apps". But I have a second install directory at "E:\Games\Oculus Apps".

Now with multiple install directories, the installer has to check all these directories.

**Comment by OmiCron07** [comment]
I found where the settings are stored in the registry: HKEY_CURRENT_USER\Software\Oculus VR, LLC\Oculus\Libraries\

![image](https://user-images.githubusercontent.com/31325575/43007742-3ad4ef7e-8c07-11e8-9bcb-7e50bf29f4f5.png)

**Comment by pcnorden** [comment]
So you basically want a dropdown menu to choose from? I'll try to whip up some code and then create a pull request.

**Comment by OmiCron07** [comment]
Or just scan each folder of the libraries node until finding the Beat Saber installation folder.

**Comment by pcnorden** [comment]
Alright, I think I have a better grasp at this now, but unfortunatly I need you to test a thing for me before I can write a pull request.

Open powershell (win + r, type "powershell" without the quotes, enter) and then type `Get-ChildItem "\\?\Volume{2544c29e-0a57-4f66-b8b5-a23e521767ef}\Games\Oculus Apps"`

Does it list all the folder in the directory and could you give me a relative path from there to the beat saber folder?

Unfortunately I dont own a Oculus so I can't test this out on my own system.

Take care =)

**Comment by OmiCron07** [comment]
So, I did the pull request #25 because it was easier to do the modifications and tests. But it was much harder than I thought because of the volume guid path that Oculus use and no simple way in C# to convert it to drive letter.

**Comment by pcnorden** [comment]
Actually had written something that did a lot of the things regarding the GUID volume thing in a previous project, but hopefully your pull request is accepted =)

Sorry I couldn't be of more help regarding your issue =(

Take care! =)

**Comment by OmiCron07** [comment]
Is it cleaner than accessing WMI or Win32 interop?

**Comment by pcnorden** [comment]
To be honest, not really sure as I'm mainly a C++ guy on linux, but from what I can read from the undocumented parts (ugh, why didn't I document something advanced) it does use WMI unfortunatly

**Comment by Umbranoxio** [comment]
I'll review your pull request and merge it, thanks for the report!
