### ISSUE TITLE
Save Data Lost

### ISSUE THREAD

**Issue by Breece1019** [Umbranoxio/BeatSaberModInstaller#22]
When Beat Saber updates, I lose all of my progress on every song, custom or not

**Comment by Deblintrake09** [comment]
I've had the same issue, after the update, all saves were lost... Also had other issues i'll post separately...

**Comment by pcnorden** [comment]
This is more related to the mods, not the mod installer. Report the issue over to them as the mod installer doesn't add code from itself to the game.

Take care =)

**Comment by Umbranoxio** [comment]
Refer to @pcnorden's comment, closed.
