### ISSUE TITLE
Custom Songs vanished once a custom song is played

### ISSUE THREAD

**Issue by StealthOrc** [Umbranoxio/BeatSaberModInstaller#23]
As described in the title: I can play one custom song - let it be any song downloaded and after I finished / played it (even on failed attempts) all custom songs vanish. Once I restart the game they all reappear. Pretty annoying to play one song and restart the whole game :/

EDIT: When I failed a song / completed it it automatically selects 100$Bills as Song. This might also help you: the songs just vanish but i found out that I can search an empty string and that I then get all songs but all the songs are bugged out, they dont preview the song and if I start them they instantly exit out and show the result screen.

**Comment by Daeke** [comment]
This has been happening to me as well since yesterday's release. Exact same symptoms, good explanation of the issue and how to repro!

**Comment by Rustybob9** [comment]
I am also having this issue.

**Comment by pcnorden** [comment]
This sounds like a songloader mod issue, not a mod installer issue as it doesn't insert code into the game.

**Comment by Umbranoxio** [comment]
Refer to @pcnorden's comment, closing this.
