### ISSUE TITLE
Black screen/No mirrored sound in monitor with new mod version...

### ISSUE THREAD

**Issue by Deblintrake09** [Umbranoxio/BeatSaberModInstaller#24]
After the update, if I play unmodded, I can hear the music and see the game, in the headset and in the monitor/speakers...

When i apply the Mod, i get the following 2 issues:

- Monitor is just black screen, no way to fix it (i can tab o other windows normally, it's not that the monitor is hung up or anything).
- The sound doesn't mirror and can only be heard either in the rift earphones, or the speakers, but not in both at once.

I'm using an Oculus Rift and a Steam version of the game.

**Comment by Umbranoxio** [comment]
This isn't related to the mod installer, the mod installer isn't the mods itself, it simply places the files for you.
