### ISSUE TITLE
Move to .NET 4.0

### ISSUE THREAD

**Issue by MicahZoltu** [Umbranoxio/BeatSaberModInstaller#3]
.NET 3.5 is super old and end-of-lifed, thus no longer included in modern OSs (e.g., Windows 10).  Recommend switching 4.x or DotNetCore so users don't have to install super old frameworks to use this.

**Comment by gunr2171** [comment]
@MicahZoltu (AFAIK) until .Net Core 3 ships, WinForms will only work on full framework.

Is there a good GUI library for Core yet? (maybe QT?).

**Comment by MicahZoltu** [comment]
I think these days most people are building UIs in HTML/CSS and throwing in an embedded browser window for rendering a desktop app.

That being said, bumping up to .NET 4 would remove the need to install a legacy framework (3.5) on modern OSs.

**Comment by Umbranoxio** [comment]
I don't exactly personally agree with this, I think it's a positive to have older versions of the framework installed, however I'll look into it.
