### ISSUE TITLE
having HEAD in the game

### ISSUE THREAD

**Issue by dglVR** [Umbranoxio/BeatSaberModInstaller#30]
Hi there. After using updater I am seeing head on my monitor. It blocks the vision. People who are with me in the same room can't see what I am seeing in the game.

**Comment by LovelyB117** [comment]
I'm also experiencing this along with the scores being deleted because to the right of the screen it is giving me the rank SSS with 100% and it won't take score anymore. I don't want that and idk why it is even in there. A glitch maybe? Alos with the big black head silhouette on my screen, I see that my hands are of an avatar I assume and that won't go away either. All I wanted were the songs. I tried to delete this mod installer from my pc and go back to the game and it's still there!  Please tell me how to get rid of this irritating issue. Thnx

**Comment by dglVR** [comment]
there is an option to erase black head from the screen. You'd have to go to steam/beatsaber settings and then do the check files thing. it will delete everything from beatsaver, including added songs :/
That's why i am still waiting for better fix.

**Comment by LovelyB117** [comment]
yea i did that just now and yup it erased everything but at least the head aint there anymore :)  ya hopefully its fixed soon

**Comment by StevenPG** [comment]
Just putting it out there, I fixed this by removing the template avatars in the plugins folder. It looks like it loads a default avatar that sits in front of the screen.

Hope this helps, just did this 2 minutes ago. I didn't have to delete the .dll, just the CustomAvatars folder.

**Comment by megalon** [comment]
I believe you can press the "Home" key on your keyboard to make your avatar invisible in first person view.

**Comment by Antrax85** [comment]
This is no issue, you just installed something you didn't configure. The HEAD you are talking about comes with the CUSTOM AVATAR PLUGIN mod.

There are 2 ways to solve this.
The first one is to eliminate the "CustomAvatar.dll" file from "Beat Saber\Plugins" folder

The second one is to configure the plugin:
Navigate to your Beat Saber install directory. There should be a file there called "cameraplus.cfg" - open it with notepad and change the line

thirdPerson=false 
to
thirdPerson=true

Now when you run the game if you are in the main menu turn around, you should see your avatar and a camera with a preview screen. Grab the white box and position it wherever you want. Also, press PageUp or PageDown on your keyboard to switch between the included avatars. In the custom avatar zip is a template for creating your own avatar if you happen to be handy with Unity and Blender. Or you can download community avatars from here:
https://discordapp.com/channels/441805394323439646/450344263453245440

Good luck!
