### ISSUE TITLE
can't start "BeatSaberModManager.exe"

### ISSUE THREAD

**Issue by Tl1000sm1234** [Umbranoxio/BeatSaberModInstaller#37]
Hello, 

when clicking on the "BeatSaberModManager.exe" I get the following message:

"The specified device, path or file cannot be accessed. You may not have sufficient privileges to access the item." (Translation from German, Win 10)

and can't start it.

With kind regards

**Comment by Umbranoxio** [comment]
The mod installer automatically runs as an administrator, sounds like you're not an administrator on your machine, therefore you cannot run the mod installer.

**Comment by Tl1000sm1234** [comment]
Hallo,

ich bin Administrator, und habe das Programm zusätzlich "Als Administrator ausführen" gestartet.

Bis Version 1.9 hatte ich keine Probleme. 

Mit freundlichen Grüßen
