### ISSUE TITLE
Error if user elevates using different account

### ISSUE THREAD

**Issue by smorgont** [Umbranoxio/BeatSaberModInstaller#41]
Environment: Windows 10 x64, Beat Saber on Steam, Vive + Oculus software installed.

If the user running the software (e.g. 'joe') is not also an administrator (for security reasons, to prevent UAC bypasses), then when 'joe' is given the UAC prompt, he will have to type in the name and password of a different user, one with local administrator powers (e.g. 'localadmin').  Thereafter, any reads to HKCU will occur under the 'localadmin' context, and consequently the SteamFinder will fail, because 'localadmin' doesn't have Steam installed.  Because Steam wasn't found, the software goes on to try to find Oculus (success!) but then the Beat Saber install isn't found, because it's on Steam.  Errors ensue.

If fixing it is too onerous, then one suggestion would be to warn users that the installing account must also be a local administrator.  Appreciate this is an edge case not likely to affect many regular users!

Thanks for the great work on this project!

**Comment by Dalet** [comment]
https://support.steampowered.com/kb_article.php?ref=9609-OBMP-2526
Looks like we could look at the `InstallPath` key in:
* `HKEY_LOCAL_MACHINE\SOFTWARE\Valve\Steam` (32 bit OS) 
* `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam` (64 bit OS)
