### ISSUE TITLE
Mod installer corrupts game and plugins don't work

### ISSUE THREAD

**Issue by Blacknwhiterainbow** [Umbranoxio/BeatSaberModInstaller#44]
On the 4th of august before playing beat saber for my first time I wanted to download that "beat saver" I heard and read of. No Issues everything worked fine as it should. 

Now yesterday suddenly that "beatsaver" button in the main menu didn't show up after starting the game. After that I tried to fix it by restart and so on without result. Today I made a save copy of the Beat Saber folder and tried to reinstall the plugin. The modinstaller was outdated so I downloaded the new one. 

Installation works fine and all the selected plugins are in the plugins folder. But when starting the game there's no sign of anything working... The beatsaver button is still missing and I can't even select something (so I can't click on solo, settings or any other button). 

I got an save copy from the beat saber folder before installing the mods and playing it for my first time as well and when using just that version everything works fine but yeah... Without the plugin its not even close as much fun :/

Any idea why this is happening?

![image](https://user-images.githubusercontent.com/42585454/44421182-19ad8800-a580-11e8-9a2c-cfd859ed1602.png)

On the picture you see the game not tracking my cursor (otherwhise the "quit" button would be white), which version and link of the modinstaller I used (top right) my Beat Saber Folder bottom left and my plugins folder (bottom right). If something else could be of use or you can't access the picture just tell me.

**Comment by wotever** [comment]
i have the same issue.
installed mod as instructed. dragged beatsaver onto IPA plugin. then ran game. buttons not working. trigger not doing anything. i am on windows mixed reality (lenovo explorer) have tried both steam vr and ateam vr beta to no avail. reinstalling beatsaber works, but cant install the mod without breaking it again. i guess ill just have to go without custom songs.. at least for now.

also, i am on beatsaber version: 0.11.1

hopefully you can help with this.. thanks heaps for creating this mod! your hard work is much appreciated.

p.s - OP did you ever figure it out on your end? cheers :)

**Comment by Blacknwhiterainbow** [comment]
Just today I completely fixed the issues. First of all I realized that I have not the latest version of beat saber and so you do (0.11.2). 

Well since I downloaded it on steam I went to the library right-clicked on the game and the preferences. There in the tab of the local files I clicked let it look for corrupt files (since I couldn't update the game the normal way because I already downloaded the latest version).

After that I again downloaded the latest version of the mod-loader and ran the installer (drag n drop the Beat Saber.exe onto the IPA.exe file is no longer needed I guess...). After that I was able to run the game with the patch & launch file. 

Since I deleted all files while trying to fix the issue I messed up the saved data from the standard and the custom songs I played before that issue happened. DON'T DO THAT AND JUST TRY TO FIX IT BY DOWNLOADING THE LATEST VERSION OF THE GAME!

So if anybody knows in which folder the scores of the played songs are saved pls tell me so I may be able to copy that files from my "save copy" I did into my Beat Saber folder

**Comment by megalon** [comment]
Yes you need the latest version of the game for the mods to work. Any mods available through the mod installer have been updated / tested to run on the latest version of the game.

Save data is actually stored in the folder `%AppData%\..\LocalLow\Hyperbolic Magnetism\Beat Saber\` not in your Beat Saber install folder.
