### ISSUE TITLE
Failed to get version

### ISSUE THREAD

**Issue by compci** [Umbranoxio/BeatSaberModInstaller#52]
(i own the game on steam)

so whenever i try to launch the mod install it pops up with the message "Failed to get version info! Please check your internet connection", and i do have my interned connected so i have no idea whats going on

**Comment by codegrad** [comment]
Same here.  Was playing "This is America" on BeatSaber.  Ran the update and found out all those songs are no longer available, so I followed instructions to run the modinstaller again and...  "Failed to get version info! Please check your internet connection"  Guess how I'm communicating to you right now.  ;)  Can we get a fix, please?

**Comment by tornadosandwich** [comment]
The game was working fine for me until i was trying to download a song today in game and the menu froze and wouldnt let me do anything, i closed the game and restarted it and after that all traces of the beatsaver mod had vanished. and now i get that same error message whenever i try to run the installer. I tried reinstalling the game and it didnt help. I hope they patch it soon, i was hoping to bring my VR to an event next weekend to let people try beat saber...

**Comment by natelink0700** [comment]
I got the same "Failed to get version info! Please check your internet connection" message, even though I definitely have internet connection. I was trying to update the mod installer to to most recent version but this is what happened and I have no idea why, but I hope it gets fixed soon.

**Comment by megalon** [comment]
Mod Saber (the site used to get the latest versions of the mods) was down for maintenance for the past ~30 minutes.
The mod installer should work just fine now if you try it again.
