### ISSUE TITLE
Beat Saber Mod Manager 2.1.2 installation update error 

### ISSUE THREAD

**Issue by gstarnet** [Umbranoxio/BeatSaberModInstaller#55]
Trying to run. 

<img width="311" alt="error" src="https://user-images.githubusercontent.com/6391981/44999580-0dfc9100-af84-11e8-920e-2a61ee5c8b49.png">

Current steam location D:\Program Files (x86)\Steam 
Windows location  C:\Windows and other programs installed under C:\Program Files (x86)\

Should allow to select installation location not fail ..

**Comment by megalon** [comment]
EDIT: I see you have the game installed in a Steam directory, not Oculus.
The installer checks both, if you have both installed on your system.

The installer uses the default install directory to check for the game, so I think you may have the Oculus default install directory set to an invalid location. It may be a folder that no longer exists, or on a drive that is no longer connected, resulting in that error.
