### ISSUE TITLE
Request: Detect/Remember chosen Plugins

### ISSUE THREAD

**Issue by WhiteZeroX** [Umbranoxio/BeatSaberModInstaller#58]
I seem to remember this working before. It would be nice if the Mod Manager would remember what extra Plugins I've chosen to install before, or just detect what is already present in the Plugins directory. That way when updating plugins you don't have to manually check them every time.

**Comment by SierraJC** [comment]
How is this still not a thing D:
It's literally such a basic thing to code

**Comment by revlisoft** [comment]
+1.  There are so many mods now it's a big pain having to reselect each and everyone.
