### ISSUE TITLE
New exe 2.1.3 not working, Beat Saber wont launch now in VR

### ISSUE THREAD

**Issue by maldorf** [Umbranoxio/BeatSaberModInstaller#59]
I was using your previous versions with great success. Today I came on to play again and saw that there was an update. I installed this latest version. Launched the game and it just sits there trying to load in VR. Eventually gave up and uninstalled Beat Saber completely. First I deleted the Beat Saber file in the Steam folder in windows and then hit uninstall off of the Steam Menu. Reinstalled it off of Steam and that runs fine without the mod.

I tried installing the new mod, 32.1.3 fresh. It did the same thing, sits there trying to load but never loads. I waited about 1 minute and usually it loads in about 5 seconds or less. Something is wrong. I am not experienced in mods, simply wanted to let you know it isn't running for me. I figure there must be more like me out there.

This is on the HTC Vive if that makes any difference.

Any ideas?

**Comment by megalon** [comment]
After launching the game, check your desktop and see if there is a popup on screen asking about your Beat Saver auth token.
If you are not interested in voting on songs, then simply click `Cancel`

This popup only occurs once.

**Comment by MudMan54** [comment]
When it's hanging, goto your desktop as itvs probably waiting for you to add a token for Beat Saber custom songs. Copy the token from the web page and paste it in  the token box.

**Comment by maldorf** [comment]
Yes! That was the problem. Previously it did not do that and I wasn't expecting something to pop up on desktop.


Im not sure exactly what a token is. I hit "no" once and got in to play the game. I quit and reloaded the game and it hung up once again with the same dialog window. This time I hit cancel and found that I can now load the game without getting the window which is great. So if I hit "no" instead of cancel the window pops up the next time you play.


WHat exactly is this feature? Ability to vote on songs? After I finished a game I noticed a number 3 next to it and a plus and minus next to it like I could vote. It was grayed out because I hit cancel, right? So if I hit "yes" I could vote there? If I hit "yes" would that same dialog window keep popping up again each time I play, like it did when I hit "no"? If I can turn on the feature with "yes" and not have the window pop up again and again then I would like to do that. 


Wondering how I can turn that on now after I hit "cancel".

**Comment by MudMan54** [comment]
Do you have a  beatsaver.com account? That may be why it pops up, I entered my token and have never had an issue since.

**Comment by maldorf** [comment]
No, I never opened up one. Maybe Ill go do that. Ive just been downloading songs. How do you go about making your own Beat Saber song? I looked around the net but couldn't seem to find any app/mod.

**Comment by Umbranoxio** [comment]
This isn't a mod installer issue, this is an issue with the BeatSaver Downloader. https://github.com/andruzzzhka/BeatSaverDownloader
