### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by evanator36** [Umbranoxio/BeatSaberModInstaller#60]
Every time I try to install the mods, it gives me this error
https://gyazo.com/d01e40d0a9986625a1bb3a754e85b0eb

Does anyone know what is going on?

**Comment by OArndt** [comment]
Yeah, same here. 
Whenever I try to launch the Mod Manager it gives me the exact same error.

**Comment by megalon** [comment]
ModSaber.ml (the site that the mod manager uses to get the mods) is down at the moment.
I'll try to post an update when it's back up.

**Comment by evanator36** [comment]
Alright thanks for the update

**Comment by OArndt** [comment]
Yeah, thanks

**Comment by evanator36** [comment]
Also does anyone know why my progress timer and score mod wont work anymore? I updated last update and my progress mod wont work when I play on the version I have now

**Comment by megalon** [comment]
Did you download the latest version of the progress counter? It had to be updated for v0.11.2 of the game
https://github.com/Strackeror/BeatSaberProgressCounter/releases

Also, for faster support, visit the support channel on the modding discord.
https://discord.gg/beatsabermods

**Comment by megalon** [comment]
The Mod Manager should work now.

Mod Saber was running a new build which isn't support by the current mod installer.
To quote lolPants from the Discord

> Because of my server crashing, it automatically defaulted to the latest build.
> I have manually reverted the version to one that is compatible with the current mod installer.

**Comment by evanator36** [comment]
Yeah the latest version worked. Thanks!
