### ISSUE TITLE
安装上之后，歌曲和节拍不一致，快到人物模型身边时自动消失了

### ISSUE THREAD

**Issue by samuelgxc** [Umbranoxio/BeatSaberModInstaller#62]
歌曲接合奏不一致
拍子在到达人物模型身边时会自动消失看不到!

**Comment by megalon** [comment]
Based on Google Translate, it sounds like you have the Hidden Note mod installed.
There should be a button on the side menu that says "Hidden Note".

Turn off "Hidden Note".
