### ISSUE TITLE
Download All Songs

### ISSUE THREAD

**Issue by bizzarrosaiyan** [Umbranoxio/BeatSaberModInstaller#63]
I apologize if this is not the correct way to ask this; I tried searching online, checked Reddit subs, and attempted as best I could figure out how to see if this was already asked here or elsewhere.

Is there a way to select to download all songs?  Ideally I would like to either continuously download or cheek for all songs I don't already have on start-up and have the option to "block" songs I chose to delete so that they would be excluded from future downloads.

**Comment by amplified1** [comment]
I feel like that would just fill up your hard drive and make a mess

**Comment by dialupdisaster** [comment]
I think this would need to be request on that particular mods github [BeatSaverDownloader](https://github.com/andruzzzhka/BeatSaverDownloader) or [BeatSaberSongLoader](https://github.com/xyonico/BeatSaberSongLoader). But I agree with @amplified1 this is probably not something anyone would want really. I could see a system for creating your own playlists or groups you could set to download or something but the song list is getting massive and the quality of a majority of the songs are...
