### ISSUE TITLE
Rotated secondary monitor

### ISSUE THREAD

**Issue by dhust** [Umbranoxio/BeatSaberModInstaller#72]
When I install the 2.1.6 mod, and with only the required mod installed, it makes it so that the secondary monitor view is rotated about 220 degrees. If I go to Steam and verify the files it states that 2 files have issues so then it fixes them and then monitor works normally again, but without the mod. I didn't have this problem with previous versions.

This doesn't happen with other games. Only Beat Saber and only if I install the 2.1.6 mod. Unfortunately, I can't install previous versions. Maybe there could be a way to allow for that in cases like this?

**Comment by megalon** [comment]
It sounds like maybe you installed the Camera Plus mod, and enabled the 3rd person camera.
I think that by default the camera can be rotated at an odd angle. If that's the case, you can see the camera behind you in game, and grab it with the laser pointer on your controller to move it around.
Check out the readme here: https://github.com/xyonico/CameraPlus

If you don't have Camera Plus installed, and this is still happening, you can try the #support channel on the Discord.
https://www.discord.gg/beatsabermods

Edit: The shortcut in game to enable the 3rd person camera (if you have Camera Plus installed) is `F1`.
I'm thinking maybe you installed camera plus, then pressed `F1` by accident.

**Comment by dhust** [comment]
I'll go to the support channel since I didn't install Camera Plus.
