### ISSUE TITLE
Install attempt results in failure

### ISSUE THREAD

**Issue by AutumnLynx** [Umbranoxio/BeatSaberModInstaller#74]
When attempting to run the installer, I was met with this message: 

Status: Install failed! 
System.ComponentModel.Win32Exception

There appeared to be more text beneath that but it did not fit in the window.

Screenshot attached for reference:

![capture](https://user-images.githubusercontent.com/44535713/47610166-57191080-da1c-11e8-9bef-d79d9c0c8dd7.PNG)

**Comment by megalon** [comment]
The **Song Loader Plugin** is supposed to be selected by default. 
There is a bug preventing the Mod Manager from doing this right now, so make sure that you select it manually before installing mods.
It is the first item in the mods list.
![image](https://user-images.githubusercontent.com/27714637/47610278-ab60c800-d9fd-11e8-8d55-a9ee022c7fe3.png)
