### ISSUE TITLE
Can't install multiplayer if window size is large enough to fit the terms

### ISSUE THREAD

**Issue by raymond-li** [Umbranoxio/BeatSaberModInstaller#8]
Reproduction (from memory, sorry):
1. Run installer
2. Go to multiplayer mod tab
3. Re-size window to fit the entire informational text
4. Press on the checkbox to acknowledge having read it
5. The pop-up dialog appears: "No you haven't, scroll down", "ಠ_ಠ"

Workaround: Re-sizing the window to be smaller than the entire text so the scrollbar is revealed and scrolling down allows the checkbox to be checked.

Another condition should probably be added here that checks if the scrollbar is enabled (gray-ed out or not) or similar.
https://github.com/Umbranoxio/BeatSaberModInstaller/blob/1358e502c81dc691e4e696d8f545f6d7dee2229d/BeatSaberModInstaller/FormMain.cs#L374

**Comment by Umbranoxio** [comment]
No longer relevant.
