### ISSUE TITLE
Linux crash on startup

### ISSUE THREAD

**Issue by unlimitedbacon** [Umbranoxio/BeatSaberModInstaller#81]
I'm trying to use the latest version (2.1.8) to update my mods. I'm running on Linux with Mono. It crashes immediately. Some earlier version worked before.

Here is a screenshot of the error message with a stack trace.
![screenshot from 2018-11-26 22-35-53](https://user-images.githubusercontent.com/3131268/49063423-2b7c7800-f1cc-11e8-989a-e803687d1541.png)

**Comment by Zamundaaa** [comment]
For me it always crashes with something about not being able to fetch version information and thus exiting.
I'd very much like to be able to update & mainly reinstall (after a Beat Saber update) without having to boot into windows before playing. It's annoying

**Comment by unlimitedbacon** [comment]
@Zamundaaa, it works fine through Wine. It's a bit tricky to navigate to the Beat Saber directory, but you can make a symlink to it in your home dir so it's easy to find.

**Comment by Zamundaaa** [comment]
There's a native executable that can do it? Lol. Didn't know
I always tried with wine and that doesn't work for me

**Comment by unlimitedbacon** [comment]
It is a .Net/C# app so the same executable can run natively using Mono or through Wine.

```
mono BeatSaberModManager.exe
```

or

```
wine BeatSaberModManager.exe
```

In the case of this particular bug, I think it is not working with Mono since it is trying to use the Windows registry. I'm guessing that Mono does not emulate the registry, but Wine does. If it's not working for you through Wine either then that must be a different issue.

**Comment by Zamundaaa** [comment]
Funnily enough it worked just fine when I used mono now
