### ISSUE TITLE
No song downloader with 2.1.8

### ISSUE THREAD

**Issue by michela** [Umbranoxio/BeatSaberModInstaller#82]
A few glitches with 2.1.8 (amazing speed getting this out!) 

* After plugin install, couldn't start Beat Saber - error - process hung
* Rebooted and reinstalled ModInstaller
* On entering game - message about plugin not loading and press CONTROL-R - worked after that but no Song Loader interface

**Comment by JoeWood02** [comment]
do you have any clue for when its is going to be back
