### ISSUE TITLE
Doesn't work after Beat Saber Update

### ISSUE THREAD

**Issue by apinanaivot** [Umbranoxio/BeatSaberModInstaller#83]
Failed to get version info! Please check your internet connection!

I have Beat Saber installed on Steam and I am connected to the internet

![image](https://user-images.githubusercontent.com/12139741/49073200-8ea4f380-f23a-11e8-850f-2a7c771f847f.png)

**Comment by apinanaivot** [comment]
Update: Apparently www.modsaber.org is down.

**Comment by megalon** [comment]
Please follow these instructions in the meantime

***Mod Saber is down right now.***
This means the Mod Manager won't work.
**However,** we can still do this the old fashioned way.

**1.** Run the game once, then close it.
**2.** Find your Beat Saber install directory. See https://wiki.assistant.moe/faq/install-folder
**3.** Download and extract this zip into your Beat Saber install directory. This zip contains all v0.12.0 mods on ModSaber.
**4.** Make sure Beat Saber is **NOT** running.
**5.** Drag the `Beat Saber` icon on top of the `IPA` icon, then launch Beat Saber normally.

https://cdn.discordapp.com/attachments/464391149616889856/516915992941559808/v0-12-0-mods-backup.zip

**Comment by aaduane** [comment]
> **However,** we can still do this the old fashioned way.
> 
> **1.** Run the game once, then close it.
> **2.** Find your Beat Saber install directory. See https://wiki.assistant.moe/faq/install-folder
> **3.** Download and extract this zip into your Beat Saber install directory. This zip contains all v0.12.0 mods on ModSaber.
> **4.** Make sure Beat Saber is **NOT** running.
> **5.** Drag the `Beat Saber` icon on top of the `IPA` icon, then launch Beat Saber normally.
> 

Can you elaborate on these instructions? I've gotten a little lost. 

Should the BeatSaberModInstaller folder from the zip be in the install directory, or should the contents of that folder be in the install directory? 

When you say the Beat Saber icon, do you mean Beat Saber.exe? 

What is the IPA icon? There's is no IPA.exe in the zip I downloaded?

**Comment by mozoarella** [comment]
@AzzyDude24601 
These are the contents of the zipfile as I've just downloaded it:
![image](https://user-images.githubusercontent.com/4236679/49081217-5efbe880-f246-11e8-9a82-073e24a36dbe.png)

There should be an IPA executable, if there isn't it may have been picked up by your anti-virus or something.

**Comment by aaduane** [comment]
> @AzzyDude24601
> These are the contents of the zipfile as I've just downloaded it:
> ![image](https://user-images.githubusercontent.com/4236679/49081217-5efbe880-f246-11e8-9a82-073e24a36dbe.png)
> 
> There should be an IPA executable, if there isn't it may have been picked up by your anti-virus or something.

Am I downloading the wrong thing? I'm downloading the latest release? This link ---> https://github.com/Umbranoxio/BeatSaberModInstaller/archive/2.1.8.zip 

...?

**Comment by mozoarella** [comment]
@AzzyDude24601 Ah, no. You're going to need the one megalon posted (https://cdn.discordapp.com/attachments/464391149616889856/516915992941559808/v0-12-0-mods-backup.zip). That's an archive of the mods on modsaber that have already been updated to work with Beat Saber version 0.12.0.

If you want to use BeatSaberModInstaller you'll have to wait until modsaber.org is back up.
