### ISSUE TITLE
ModSaber is back online, but song downloader disappeared from in-game interface

### ISSUE THREAD

**Issue by aaduane** [Umbranoxio/BeatSaberModInstaller#85]
With the latest update (2.1.8), the song downloader interface which used to appear in-game has disappeared and now the only way to add custom songs is to download them manually outside the game and add them to the directory. 

Is this a bug, or does the song downloader need to be updated to work with 2.1.8?

**Comment by brianjp93** [comment]
This is from the beat saber discord announcement.  The UI has changed, so it may take a few days to update.  It is not a bug.

------

Mods Status
:white_check_mark: Songloader
:x: Custom Leaderboards (Steam) Score submission has been disabled for now
:x: Custom Leaderboards (Oculus Home) WIP
:x: Ingame Downloader The UI has changed a lot this time, may take several days to update

:x: Custom Sabers: WIP
:x: CustomAvatars: WIP
:ballot_box_with_check: Custom Platforms Awaiting upload to modsaber

:white_check_mark: Camera Plus
:white_check_mark: Full Combo Display
:white_check_mark: Custom Colors

**Comment by aaduane** [comment]
Ah, I will join the Discord server. Thank you for the information.

**Comment by brianjp93** [comment]
np.  Here's the modding discord group
https://discordapp.com/invite/6JcXMq3
