### ISSUE TITLE
Older Version of ModManager

### ISSUE THREAD

**Issue by teamoney6667** [Umbranoxio/BeatSaberModInstaller#86]
When I installed the BeatSaberModManager.exe, it was an old version. I'm trying to get custom sabers, but there is no custom saber box to check and download. I could be wrong, but in the top right of the manager app, it says it is version 0.12.0p 1. if that is not the version, then there is still no custom saber box to check. I went to other versions and got the custom saber folder but when I put the sabers in and start the game, there is no way to choose the sabers. Also with this version, the blocks disappear before I can hit them.

**Comment by UntouchedOdin0** [comment]
Hi, the latest version is 0.12.0p1 with the ModManager, the reason that custom sabers isn't in there yet is because they're working on updating the mod to the latest version. :)
