### ISSUE TITLE
Download Timed Out

### ISSUE THREAD

**Issue by Spartan5556** [Umbranoxio/BeatSaberModInstaller#9]
I've downloaded about 10-20 songs prior to getting this message. Can anyone tell me why this timeout keeps popping up?

**Comment by Umbranoxio** [comment]
This project is for installing the mods only, not support for existing mods, it sounds like you have an issue with the BeatSaverDownloader here: https://github.com/andruzzzhka/BeatSaverDownloader

I'll be closing this issue, feel free to create an issue over at the repo linked above.
