### ISSUE TITLE
Mods seem to weaken haptics.

### ISSUE THREAD

**Issue by cedws** [Umbranoxio/BeatSaberModInstaller#90]
This a bit of an odd issue and is difficult to reliably test. I think haptics might be weaker with mods installed after using BeatSaberModInstaller.
I'm using the tool to install:
```
Song Loader Plugin
ScoreSaber
BeatSaver Downloader
Camera Plus
SongBrowser Plugin
```
Sometimes the haptics feel so weak that I can barely feel them. If I then verify the installation through Steam which repairs some files (and uninstalls the mods), the haptics feel strong again, but this might just be confirmation bias.
I'm playing using an Oculus Rift, and running Beat Saber with `-vrmode oculus`.

**Comment by viscoci** [comment]
I know that lowered Frame Rates will cause the haptics to get weaker/ less consistent. Adding an extra camera may be just enough to bring your frame rate to fluctuate below the recommended 90fps

**Comment by cedws** [comment]
Thanks @viscoci.
I still haven't figured this one out. It's really strange. Sometimes the game will start with weak haptics, and other times I'll start the game and the haptics will be strong. If I replug a few USB cables while playing, the haptics sometimes change. But it seems to be happening even without mods, so I'm closing this issue.
